// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeTSglDwcrUHQBF0tYVTPcBlSaCv-GtOo',
    appId: '1:827711607891:web:3ffc50494f8da5a34be2a6',
    messagingSenderId: '827711607891',
    projectId: 'instagram-clone-156ef',
    authDomain: 'instagram-clone-156ef.firebaseapp.com',
    storageBucket: 'instagram-clone-156ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB6k1nHGH9L_70UOzfXKRvpk33-WPuLQ0',
    appId: '1:827711607891:android:060235e64efd1fbe4be2a6',
    messagingSenderId: '827711607891',
    projectId: 'instagram-clone-156ef',
    storageBucket: 'instagram-clone-156ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbyBgJOjszzfNEYNkiDiA-LQOTOsC5fyg',
    appId: '1:827711607891:ios:ab16abe8b706828a4be2a6',
    messagingSenderId: '827711607891',
    projectId: 'instagram-clone-156ef',
    storageBucket: 'instagram-clone-156ef.appspot.com',
    iosBundleId: 'com.example.instagramCloneApp',
  );
}
